#!/bin/zsh -ue

# Original code in autohotkey.ahk
# $F2:: winActivateExe(terminal, "", "run LS_COLORS=$LS_COLORS:'ow=1;34:tw=1;34:' tmux attach 2> /dev/null || LS_COLORS=$LS_COLORS:'ow=1;34:tw=1;34:' tmux")

export LS_COLORS=$LS_COLORS:'ow=1;34:tw=1;34:' 

if [[ -z $TMUX ]]; then
    echo $PATH | grep -q "$HOME/.local/lib/bash" || export PATH=$HOME/.local/lib/bash:$PATH
    echo $PATH | grep -q "$HOME/bin"             || export PATH=$HOME/bin:$PATH
    tmux attach 2> /dev/null || exec tmux
fi
