#!/bin/bash
#-----------------------------------------------------------------------------------------------
# Autohotkey library
#-----------------------------------------------------------------------------------------------
activeWinId() {
    windowId=`xdotool getactivewindow`
    result=$?
    echo $windowId
    return $result
}

# @param class/title name
# @param ahk_title
isWinActive() {
    if [[ -z ${2-} ]]; then # class
        xprop -id $(xdotool getactivewindow) | grep -q WM_CLASS.*=.*$1
        return $?
    else # title
        title=`xdotool getactivewindow getwindowname`
        if echo $title | grep -E $1; then
            return 0
        else
            return 1
        fi
    fi
}

# @param class name
winExist() {
    xdotool search --class $1
    return $?
}

winActivate() {
    if [[ -z ${2-} ]]; then
        xdotool search --class $1 windowactivate
    else
        xdotool search --name  $1 windowactivate
    fi
}

isActiveWinFloating() {
    xprop -id $(xdotool getactivewindow) | grep -q "WM_STATE.*STICKY"
}

isWorkspaceEmpty() {
    (! xdotool getactivewindow) || isActiveWinFloating
}

# xdotool with the ability to bypass i3 keygrabbing
xdotool-forward() {
    i3-msg 'mode " "'
    xdotool $@
    i3-msg 'mode "default"'
}


#-----------------------------------------------------------------------------------------------
# Shortcut implementation
#-----------------------------------------------------------------------------------------------
deleteWord() {
	if isWinActive URxvt; then
        xte 'keyup p' 'keydown Control_L' 'key w' 'keyup Control_L'
	else
        xte 'keyup p' 'keydown Control_L' 'key BackSpace' 'keyup Control_L'
	fi
}

deleteLine() {
	if isWinActive URxvt; then
        xte 'keyup u' 'keydown Control_L' 'key u' 'keyup Control_L'
	else
        # ctrl+shift+backspace (delete before) and ctrl+shift+del (delete after)
        xte 'keyup u' 'keydown Control_L' 'keydown Shift_L' 'key BackSpace' 'key Delete' 'keyup Shift_L' 'keyup Control_L'
	fi
}

closeTabOrWindow() {
    if isWinActive Google-chrome || isWinActive Firefox || isWinActive Brave-browser; then
        xte 'keydown Control_L' 'key w' 'keyup Control_L'
    else
        xte 'keydown Alt_L' 'key grave' 'keyup Alt_L'
    fi
}

# floatingToggled() {
#     # When mpv got focused (mpv always floating), go to full screen
#     if isWinActive mpv; then
#         i3-msg fullscreen
#     fi
# }

pageup() {
    if isWinActive Google-chrome || isWinActive VIM$ ahk_title; then
        xdotool key ctrl+b
    elif isWinActive URxvt; then
		xdotool key shift+Prior
    else
        xdotool key Prior
    fi
}

pagedown() {
    if isWinActive Google-chrome || isWinActive VIM$ ahk_title; then
        xdotool key ctrl+f
    elif isWinActive URxvt; then
		xdotool key shift+Next
    else
        xdotool key Next
    fi
}

scroll() {
    if isWinActive URxvt && ! isWinActive VIM$ ahk_title; then
		xdotool keyup $2 key shift+$1
    else
        xdotool keyup $2 key $1
    fi
}

pause() {
    if winExist mpv; then
		echo cycle pause | socat - ~/.config/mpv/socket
    else
		cmus-remote -u && pkill -RTMIN+12 i3blocks
    fi
}

nextTrack() {
    if winExist mpv; then
		echo playlist-next | socat - ~/.config/mpv/socket
    else
		cmus-remote -n && pkill -RTMIN+12 i3blocks
    fi
}

prevTrack() {
    if winExist mpv; then
		echo playlist-prev | socat - ~/.config/mpv/socket
    else
		cmus-remote -r && pkill -RTMIN+12 i3blocks
    fi
}

#
# i3 and VIM navigation integration (navigation/movement/resizing)
#
focusWindow() {
    direction=$1
	case $direction in
		left)
			navKey=h;;
		right)
			navKey=l;;
		up)
			navKey=k;;
		down)
			navKey=j;;
	esac
    if isWinActive VIM$ ahk_title || isWinActive "^vim " ahk_title \
       || isWinActive Code \
       || isWinActive ^Notebook$ ahk_title; then
        xdotool-forward keyup $navKey key $navKey
    elif isWinActive ^ranger ahk_title && [[ $direction == 'left' || $direction == 'right' ]]; then
        xdotool-forward keyup $navKey key $navKey
    else
		i3-msg "focus $direction"
    fi
}

moveWindow() {
    direction=$1
	case $direction in
		left)
			navKey=h;;
		right)
			navKey=l;;
		up)
			navKey=k;;
		down)
			navKey=j;;
	esac
    if isWinActive VIM$ ahk_title || isWinActive "^vim " ahk_title \
       || isWinActive Code \
       || isWinActive ^Notebook$ ahk_title; then
        xdotool-forward keyup $navKey key $navKey
    else
		i3-msg "move $@"
    fi
}

resizeWindow() {
    direction="$1 $2"
	case $direction in
		"shrink width")
			navKey=h;;
		"grow width")
			navKey=l;;
		"grow height")
			navKey=k;;
		"shrink height")
			navKey=j;;
	esac
    if isWinActive VIM$ ahk_title || isWinActive "^vim " ahk_title \
       || isWinActive Code \
       || isWinActive ^Notebook$ ahk_title; then
        echo "${@:3}" > /tmp/vim-tmux-i3-integration # Passing size parameters to be consumed.
        xdotool-forward keyup $navKey key $navKey
    else
		i3-msg "resize $@"
    fi
}

# Use app's built-in fullscreen mode if available
toggleFullscreen() {
    # if isWinActive Google-chrome || isWinActive Firefox || isWinActive Brave-browser; then
    #     xdotool keyup f Alt key F11
    # elif isWinActive Code; then # Toggle zen mode for vscode
    # if isWinActive Code; then # Toggle zen mode for vscode
    #     xdotool keyup f Alt key ctrl+shift+z
    # else
    #     i3-msg "fullscreen toggle"
    # fi
    i3-msg "fullscreen toggle"
}

mediaPlayerFullscreen() {
    i3-msg '[class="^mpv"] fullscreen toggle, scratchpad show'
    # i3-msg '[class="^mpv"] fullscreen toggle' && i3-msg '[class=mpv] scratchpad show'
    # i3-msg '[class="^mpv"] scratchpad show' && sleep 1.5 && i3-msg '[class="^mpv"] fullscreen'
}

F1() {
    i3-msg 'workspace number "1: Web "'

    if i3-msg -t get_workspaces | jq '.[] | select(.num == 1) .focused' | grep 'true'; then
        if ! xdotool getactivewindow; then
            # Chrome has a bug that won't enable dark mode for webpages on Linux: https://bugs.chromium.org/p/chromium/issues/detail?id=889087
            google-chrome --force-dark-mode
        fi
    fi
}

F2() {
    i3-msg 'workspace number "2: Term "'

    if i3-msg -t get_workspaces | jq '.[] | select(.num == 2) .focused' | grep 'true'; then
        if ! xdotool getactivewindow; then
            urxvtc
        fi
    fi
}

# File manager
F3() {
    i3-msg 'workspace number "3: File "'

    # If workspace 3 has no ranger instance, create one
    if i3-msg -t get_workspaces | jq '.[] | select(.num == 3) .focused' | grep 'true'; then
        if ! isWinActive ^ranger ahk_title; then
            urxvtc -e ranger $HOME
        fi
    fi
}

# Lutris (Linux gaming)
F10() {
    i3-msg 'workspace number "10: G "'

    if i3-msg -t get_workspaces | jq '.[] | select(.num == 10) .focused' | grep 'true'; then
        if ! isWinActive Lutris; then
            lutris
        fi
    fi
}

toggleMouseMode() {
    file='/tmp/mouse-alt'
    if [ -f $file ]; then
        rm $file
        notify-send.sh --close=10 # notify-send.sh supports expiration time and closing notifications (https://askubuntu.com/questions/110969/notify-send-ignores-timeout)
    else
        touch $file
        notify-send.sh -t 0 -r 10 -u critical Alt Mouse
    fi

    activate-hotkeys
}


#-----------------------------------------------------------------------------------------------
# Execute
# TODO: Input validation
#-----------------------------------------------------------------------------------------------
[[ $# == 0 ]] || $@


# Deprecated: result is unreliable. e.g. getting incorrect pid from sxiv
# activeWinPid() {
#     pid=`xdotool getactivewindow getwindowpid`
#     result=$?
#     echo $pid
#     return $result
# }
