#!/bin/bash
#-------------------------------------------------------------------------------------------------
# Check whether internal or external monitor is used and dispatch to corresponding handling script
#-------------------------------------------------------------------------------------------------
if [ -f ~/.config/hardware/external-displayrc ]; then
	source ~/.config/hardware/external-displayrc

	if xrandr | grep -q "\<$interface\> connected"; then
		external-monitor-control $@
	else
		internal-monitor-control $@
	fi
else
    echo -e "[Error] Cannot perform action: external-displayrc not found in ~/.config/hardware"
    exit 1
fi
