#!/bin/bash -ue
cached_spec=/tmp/display1

# Force re-generate display information regardless of cache
[ $# -eq 1 ] && [[ $1 == "-f" ]] && rm -f $cached_spec

# If cached spec exist, use it.
if [ -f $cached_spec ]; then
    source $cached_spec
    source ~/.config/hardware/$model
    return 0
fi

# Read panel model information and cache it for later use
read_display_connection() {
    local ddc_info="`ddcutil detect`"

    model=`echo "$ddc_info" | grep "Model:" | awk '{print $2}'`
    i2c_bus=`echo "$ddc_info" | grep "I2C bus" | awk '{print $3}' | sed 's/.*-//'`
}

read_monitor_spec() { 
    local xrandr_info=`xrandr` # Store xrandr result for more intormation parsing
    interface=`echo "$xrandr_info" | grep -w connected | awk '{print $1}'`

    [ -f ~/.config/hardware/$model ] && source ~/.config/hardware/$model || return 1; 
}

cache_display_spec() {
    echo "model=$model
    i2c_bus=$i2c_bus" > $cached_spec
    echo "interface=$interface" >> $cached_spec
}

exec_xrandr() {
    local cmd="xrandr --output $interface --mode $resolution --scale $scale --rate $refresh_rate"
    eval $cmd
}

model=""
i2c_bus=""
interface=""
read_display_connection && read_monitor_spec && cache_display_spec || return 1
# exec_xrandr


#------------------------------------------------------------------------------
# Legacy
#------------------------------------------------------------------------------
# Description: If external display is connected, use external display only. If not, use internal display only
# NOTE: Intel driver won't output full RGB on external monitor: https://wiki.archlinux.org/index.php/Intel_graphics#Weathered_colors_(color_range_problems)
# Caution: external-displayrc and internal-displayrc both define same set of variables

# # Read configuration
# if [ -f ~/.config/hardware/gpurc ]; then
#     source ~/.config/hardware/gpurc
# else
#     exit 1
# fi
# if [ -f ~/.config/hardware/external-displayrc ]; then
# 	source ~/.config/hardware/external-displayrc
# else
#     # If no multi-monitor setup, no need to change xrandr configuration
#     exit 1
# fi

# # Assemble xrandr command
# if xrandr | grep "\<$interface\> connected"; then
#     # External display connected
#     cmd="xrandr --output $interface --mode $resolution --scale $scale --rate $refresh_rate"
# 	  if [ -f ~/.config/hardware/internal-displayrc ]; then
# 		source ~/.config/hardware/internal-displayrc
#         if [ ! -z $interface ]; then
# 			cmd="$cmd --output $interface --off"
#         fi
# 	  fi
# 	  if [ $isIntelGpu = true ]; then
#         cmd="$cmd --set \"Broadcast RGB\" \"Full\""
#     fi
# else
#     # External display not connected, only internal display connected
# 	  if [ ! -f ~/.config/hardware/internal-displayrc ]; then
#         # External display not connected , no internal display configuration
#         exit 1
#     fi
#     source ~/.config/hardware/internal-displayrc
#     if [ -z $interface ]; then
#         cmd="xrandr --output $interface --mode $resolution --scale $scale"
#     fi
# fi

