#!/bin/bash

# Resolution
resolution="1920x1080"
scale="1x1"
refresh_rate=120
is_high_dpi=false

# Monitor spec
brightness_feature_id=10
color_temperature_feature_id=14
contrast_feature_id=12

# Brightness/color/contrast temperature control
is_reading_mode=false
is_gaming_mode=false
brightness_step=5
contrast_step=5
reading_brightness=0
video_brightness=20
gaming_brightness=35
color_temperature_reading=0xb # User1
color_temperature_video=5 # 5000K
color_temperature_gaming=5 # 5000K
reading_contrast=50
video_contrast=50
gaming_contrast=50
