#!/bin/bash

# Resolution
resolution="3840x2160"
scale="1.33333x1.33333" # 2/1.5=1.333 => scale 150%
# scale="1.6x1.6" # 2/1.25=1.6 => scale 125%
# scale="1x1"
refresh_rate=60
is_high_dpi=true

# Monitor spec
brightness_feature_id=10
color_temperature_feature_id=14
contrast_feature_id=12

# Brightness/color temperature control
is_reading_mode=true
is_game_mode=false
brightness_step=5
contrast_step=5
reading_brightness=5
video_brightness=20
game_brightness=40
color_temperature_reading=4 # 6500K
color_temperature_video=5 # 5000K
color_temperature_game=5 # 5000K
reading_contrast=50
video_contrast=50
game_contrast=50
