#!/bin/bash

# Example for $XDG_CONFIG_HOME/sxiv/exec/image-info
# Called by sxiv(1) whenever an image gets loaded.
# The output is displayed in sxiv's status bar.
# Arguments:
#   $1: path to image file
#   $2: image width
#   $3: image height

s="    " # field separator

date=$(exiftool -S -CreateDate $1)
if [ -z $date ]; then # If creation date does not exist, fall back to use modify date which all photos have.
    date=$(exiftool -S -FileModifyDate $1)"*" # If using modification date, "*" is appended.
fi

date=$(echo $date \
    | sed -r 's/\+[0-9]{2}:[0-9]{2}//g' `# Remove time zone` \
    | sed -r 's/([0-9]+):([0-9]+):([0-9]+)/\1\/\2\/\3,/' `# Date format separator from ":" to "/"` \
    | sed -r 's/20([0-9]+\/[0-9]+\/[0-9]+,)/\1/' `# Yes 20xx to xx` \
    | sed -r 's/([0-9]+):([0-9]+):([0-9]+)/\1\:\2/' `# Remove second from time` \
    | awk '{printf "%s%s'"$s"'", $2, $3}' \
    )
    # | sed 's/,/ /' `# Add space between date and time` \

tags=$(exiftool -S -Filename -ImageSize -FileSize $1 \
    | awk '{printf "%s%s'"$s"'", $2, $3}' \
    )
    # | sed "s/$s$//" `# Remove trailing separator`
echo "${tags}${date}"


#-------------------------------------------------------------------------------------
# Example
#-------------------------------------------------------------------------------------
# filename=$(basename "$1")
# filesize=$(du -Hh "$1" | cut -f 1)

# The '[0]' stands for the first frame of a multi-frame file, e.g. gif.
# geometry=$(identify -format '%wx%h' "$1[0]")

# tags=$(exiv2 -q pr -pi "$1" | awk '$1~"Keywords" { printf("%s,", $4); }')
# tags=${tags%,}

# echo "${filesize}${s}${geometry}${tags:+$s}${tags}${s}${filename}"

